var vuejsall= new Vue({
el: '#vuejsall',
data: {    



//電腦版banner 
//textbr:'黑白X丹寧', //新增段落
banneritem: [
    {   id: 0, 
        link:'https://www.chung-yo.com/promotion/2681',
        img:'images/banner/108-7-09/【艾杜紗】自然系女孩 簡單保養75折起/艾杜紗_1220.jpg',
        title:'自然系女孩',
        text: '簡單保養75折起',
    },
    {   id: 1, 
        link:'https://www.chung-yo.com/promotion/2677',
        img:'images/banner/108-7-09/夏日輕保養 水亮美肌5折起/BN_1220.jpg',
        title:'夏日輕保養',
        text: '水量美肌5折起',
    },
    {   id: 2, 
        link:'https://www.chung-yo.com/promotion/2686',
        img:'images/banner/108-7-09/疾走青春! 暑期專屬8折起/1220x500.jpg',
        title:'疾走青春',
        text: '暑期專屬8折起',
    },
    {   id: 3, 
        link:'https://www.chung-yo.com/promotion/2706',
        img:'images/banner/108-7-09/擺脫炎夏煩躁-草本舒活4折起/擺脫炎夏煩躁-草本舒活4折起_1220.jpg',
        title:'擺脫夏日煩躁',
        text: '草本舒活4折起',
    },
    {   id: 4, 
        link:'https://www.chung-yo.com/promotion/2670',
        img:'images/banner/108-7-09/暑假FUN肆玩-兒童玩具6折起/暑假FUN肆玩-兒童玩具6折起_1220(百貨直購).jpg',
        title:'暑假Fun肆玩',
        text: '兒童玩具6折up',
    },
    {   id: 5, 
        link:'https://www.chung-yo.com/promotion/2705',
        img:'images/banner/108-7-09/暑假出遊美包特搜3折起/1220x500.jpg',
        title:'暑假出遊',
        text: '美包特搜6折起',
    },
    {   id: 6, 
        link:'https://www.chung-yo.com/promotion/2669',
        img:'images/banner/108-7-09/度假休閒風 零失誤特輯6折起/1220x500.jpg',
        title:'度假休閒風',
        text: '零失誤特輯6折起',
    },
    {   id: 7, 
        link:'https://www.chung-yo.com/promotion/2710',
        img:'images/banner/108-7-09/E-WEAR/1220x500.jpg',
        title:'E-WEAR',
        textbr:'文青時尚LOOK', //新增段落
        text: '全面6折起',
    },
    {   id: 8, 
        link:'https://www.chung-yo.com/event/restaurant/',
        img:'images/banner/108-7-09/food/1220x500.jpg',
        title:'中友人氣餐廳',
        text: '精選套餐74折起',
    },
],
//手機板banner 
banneritemm: [
   
    {   id: 0, 
        text: '簡單保養75折起',
        link:'https://www.chung-yo.com/promotion/2681',
        img:'images/banner/108-7-09/【艾杜紗】自然系女孩 簡單保養75折起/艾杜紗_800.jpg',
    },

    {   id: 1, 
        text: '水量美肌5折起',
        link:'https://www.chung-yo.com/promotion/2677',
        img:'images/banner/108-7-09/夏日輕保養 水亮美肌5折起/BN_800.jpg',
    },
    {   id: 2, 
        text: '暑期專屬8折起',
        link:'https://www.chung-yo.com/promotion/2686',
        img:'images/banner/108-7-09/疾走青春! 暑期專屬8折起/800x500.jpg',
    },
    {   id: 3, 
        text: '草本舒活4折起',
        link:'https://www.chung-yo.com/promotion/2706',
        img:'images/banner/108-7-09/擺脫炎夏煩躁-草本舒活4折起/擺脫炎夏煩躁-草本舒活4折起_800.jpg',
    },
    {   id: 4, 
        text: '兒童玩具6折up',
        link:'https://www.chung-yo.com/promotion/2670',
        img:'images/banner/108-7-09/暑假FUN肆玩-兒童玩具6折起/暑假FUN肆玩-兒童玩具6折起_800x500.jpg',
    },
    {   id: 5, 
        text: '美包特搜6折起',
        link:'https://www.chung-yo.com/promotion/2705',
        img:'images/banner/108-7-09/暑假出遊美包特搜3折起/800x500.jpg',
    },
    {   id: 6, 
        text: '零失誤特輯6折起',
        link:'https://www.chung-yo.com/promotion/2669',
        img:'images/banner/108-7-09/度假休閒風 零失誤特輯6折起/800x500.jpg',
    },
    {   id: 7, 
        text: '文青時尚LOOK,全面6折起',
        link:'https://www.chung-yo.com/promotion/2710',
        img:'images/banner/108-7-09/E-WEAR/800x500.jpg',
    },
    {   id: 8, 
        text: '精選套餐74折起',
        link:'https://www.chung-yo.com/event/restaurant/',
        img:'images/banner/108-7-09/food/800x500.jpg',
    },
],







//1.化妝品 商品資訊
skincareitem:[
    {
        id:'229074',
        link:'https://www.chung-yo.com/Product/229074',
        img:'https://www.chung-yo.com/localStorage/market/229074/image/MAI_175316078_X400X400.jpg',
        text:'【LA MER】奇蹟煥采氣墊粉霜組',
        pricetext:'特價',
        price:'4200',
        },
        {
        id:'253925',
        link:'https://www.chung-yo.com/Product/253925',
        img:'https://www.chung-yo.com/localStorage/market/253925/image/MAI_114045630_X400X400.jpg',
        text:'【Kanebo】COFFRET D΄OR 玩色我型眼頰彩霜',
        pricetext:'特價',
        price:'675',
        },
        {
        id:'254431',
        link:'https://www.chung-yo.com/Product/254431',
        img:'https://www.chung-yo.com/localStorage/market/254431/image/MAI_104617947_X400X400.jpg',
        text:'【BIOTHERM碧兒泉】粉綠粉亮保濕露嘗鮮組',
        pricetext:'特價',
        price:'1200',
        },
        {
        id:'257133',
        link:'https://www.chung-yo.com/Product/257133',
        img:'https://www.chung-yo.com/localStorage/market/257133/image/MAI_135252939_X400X400.jpg',
        text:'【su:m37】活酵保濕光澤精華凝露組',
        pricetext:'特價',
        price:'1980',
        },
        {
        id:'257135',
        link:'https://www.chung-yo.com/Product/257135',
        img:'https://www.chung-yo.com/localStorage/market/257135/image/MAI_135754734_X400X400.jpg',
        text:'【KOSE】雪肌精透亮潤白組',
        pricetext:'特價',
        price:'900',
        },
],

        //化妝品 熱門標籤
        makeuptypeitem:[
            {   id: 0, 
                text: '3INA',
                titletext:'更多3INA商品',
                link:'https://www.chung-yo.com/Product/CategoryS/15263',
            },   
            {   id: 1, 
                text: 'Burt\'s Bees',
                titletext:'更多Burt\'s Bees商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4727',
            },   
            {   id: 2, 
                text: 'ESTEE LAUDER',
                titletext:'更多ESTEE LAUDER商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14811',
            },    
            {   id: 3, 
                text: 'ettusais艾杜紗',
                titletext:'更多ettusais艾杜紗',
                link:'https://www.chung-yo.com/Product/CategoryF/4797',
            },
            {   id: 4, 
                text: 'KRYOLAN歌劇魅影',
                titletext:'更多KRYOLAN歌劇魅影商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14783',
            },
            {   id: 5, 
                text: 'LA MER',
                titletext:'更多LA MER商品',
                link:'https://www.chung-yo.com/Product/CategoryS/15171',
            },
        ],
    


//2.名品 商品資訊
internationalitem:[
   
{
    id:'257173',
    link:'https://www.chung-yo.com/Product/257173',
    img:'https://www.chung-yo.com/localStorage/market/257173/image/MAI_160908447_X400X400.jpg',
    text:'【Samsonite】Varro系列25吋孔雀藍色中箱',
    pricetext:'特價',
    price:'9180',
    },
    {
    id:'257174',
    link:'https://www.chung-yo.com/Product/257174',
    img:'https://www.chung-yo.com/localStorage/market/257174/image/MAI_161925027_X400X400.jpg',
    text:'【ALDO】拼色編織肩背包',
    pricetext:'特價',
    price:'1580',
    },
    {
    id:'257175',
    link:'https://www.chung-yo.com/Product/257175',
    img:'https://www.chung-yo.com/localStorage/market/257175/image/MAI_162702090_X400X400.jpg',
    text:'【SJ&J】The Leather Satchel Co.英國手工牛皮潮流三用相機包',
    pricetext:'特價',
    price:'7500',
    },
    {
    id:'257177',
    link:'https://www.chung-yo.com/Product/257177',
    img:'https://www.chung-yo.com/localStorage/market/257177/image/MAI_164047284_X400X400.jpg',
    text:'【PANDORA】Disney獅子王辛巴與娜娜串飾',
    pricetext:'特價',
    price:'2880',
    },
    {
    id:'257213',
    link:'https://www.chung-yo.com/Product/257213',
    img:'https://www.chung-yo.com/localStorage/market/257213/image/MAI_102347165_X400X400.jpg',
    text:'【盧亞香水】Chloe’芳心之旅女性淡香水組',
    pricetext:'特價',
    price:'3750',
    },
],

        //名品 熱門標籤
        internationaltypeitem: [
            {   id: 0, 
                text: 'SJ&J',
                titletext:'更多SJ&J商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=SJ%26J&',
            },
            {   id: 1, 
                text: 'FOSSIL',
                titletext:'更多FOSSIL商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=FOSSIL&',
            },
            {   id: 2, 
                text: 'Gloria',
                titletext:'更多Gloria商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=Gloria&',
            },
            {   id: 3, 
                text: 'COCCINELLE',
                titletext:'更多COCCINELLE商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=COCCINELLE',
            },
            {   id: 4, 
                text: 'Chloe',
                titletext:'更多Chloe商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=Chloe',
            },
            {   id: 5, 
                text: 'Samsonite',
                titletext:'更多Samsonite商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=Samsonite',
            },
        ],
    

//3.服裝 商品資訊
accessoriesitem:[
    {
        id:'250142',
        link:'https://www.chung-yo.com/Product/250142',
        img:'https://www.chung-yo.com/localStorage/market/250142/image/MAI_213940527_X400X400.jpg',
        text:'【SISLEY】輕柔V領連身裙',
        pricetext:'特價',
        price:'3580',
        },
        {
        id:'255799',
        link:'https://www.chung-yo.com/Product/255799',
        img:'https://www.chung-yo.com/localStorage/market/255799/image/MAI_105447201_X400X400.jpg',
        text:'【 B.T Rose】真皮手提側背兩用包 贈真皮手拿包',
        pricetext:'特價',
        price:'2800',
        },
        {
        id:'255971',
        link:'https://www.chung-yo.com/Product/255971',
        img:'https://www.chung-yo.com/localStorage/market/255971/image/MAI_105151701_X400X400.jpg',
        text:'【名人】都會叢林四件式泳衣',
        pricetext:'特價',
        price:'1480',
        },
        {
        id:'255976',
        link:'https://www.chung-yo.com/Product/255976',
        img:'https://www.chung-yo.com/localStorage/market/255976/image/MAI_105639636_X400X400.jpg',
        text:'【奧可那】夏日花卉四件式泳衣(附泳帽)',
        pricetext:'特價',
        price:'1280',
        },
        {
        id:'256051',
        link:'https://www.chung-yo.com/Product/256051',
        img:'https://www.chung-yo.com/localStorage/market/256051/image/MAI_104325155_X400X400.jpg',
        text:'【pierre cardin】時尚金屬拉扣設計後背包(2色)',
        pricetext:'特價',
        price:'7080',
        },
        {
        id:'256699',
        link:'https://www.chung-yo.com/Product/256699',
        img:'https://www.chung-yo.com/localStorage/market/256699/image/MAI_104526758_X400X400.jpg',
        text:'【ERaMIE】時尚無袖洋裝',
        pricetext:'特價',
        price:'4700',
        },
        {
        id:'256725',
        link:'https://www.chung-yo.com/Product/256725',
        img:'https://www.chung-yo.com/localStorage/market/256725/image/MAI_092527572_X400X400.png',
        text:'【BROADWAY】飄逸感遮陽罩衫',
        pricetext:'特價',
        price:'1680',
        },
        {
        id:'256751',
        link:'https://www.chung-yo.com/Product/256751',
        img:'https://www.chung-yo.com/localStorage/market/256751/image/MAI_145053043_X400X400.jpg',
        text:'【kila kila】珍珠花朵造型耳環',
        pricetext:'特價',
        price:'690',
        },
        {
        id:'256873',
        link:'https://www.chung-yo.com/Product/256873',
        img:'https://www.chung-yo.com/localStorage/market/256873/image/MAI_111343255_X400X400.jpg',
        text:'【H2O】典雅修身長版罩衫',
        pricetext:'特價',
        price:'2680',
        },
        {
        id:'257114',
        link:'https://www.chung-yo.com/Product/257114',
        img:'https://www.chung-yo.com/localStorage/market/257114/image/MAI_113513403_X400X400.jpg',
        text:'【California Republic】卡通玩味短版上衣',
        pricetext:'特價',
        price:'1080',
        },
        
],

        //服裝 熱們標籤
        accessoriestypeitem:[
            {   id: 0, 
                text: 'GUESS服飾',
                titletext:'更多GUESS服飾商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4783',
            },
            {   id: 1, 
                text: 'satana',
                titletext:'更多satana商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4784',
            },
            {   id: 2, 
                text: 'MAGY',
                titletext:'更多MAGY商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4771',
            },
            {   id: 3, 
                text: 'CUMAR',
                titletext:'更多CUMAR商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14878',
            },
            {   id: 4, 
                text: 'E-WEAR',
                titletext:'更多E-WEAR商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4928',
            },
            {   id: 5, 
                text: 'H2O',
                titletext:'更多H2O商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4919',
            },
        ],


            


//4.童裝 婦幼親子 商品資訊
kidsbabyitem: [
    {
        id:'257117',
        link:'https://www.chung-yo.com/Product/257117',
        img:'https://www.chung-yo.com/localStorage/market/257117/image/MAI_115847827_X400X400.jpg',
        text:'【Roberta di Camerino】清涼洋裝',
        pricetext:'特價',
        price:'1290',
        },
        {
        id:'257121',
        link:'https://www.chung-yo.com/Product/257121',
        img:'https://www.chung-yo.com/localStorage/market/257121/image/MAI_130438512_X400X400.jpg',
        text:'【安妮公主】簡單風上衣',
        pricetext:'特價',
        price:'690',
        },
        {
        id:'257126',
        link:'https://www.chung-yo.com/Product/257126',
        img:'https://www.chung-yo.com/localStorage/market/257126/image/MAI_132139197_X400X400.jpg',
        text:'【麗嬰房】竹纖維雙層大方巾',
        pricetext:'特價',
        price:'590',
        },
        {
        id:'257130',
        link:'https://www.chung-yo.com/Product/257130',
        img:'https://www.chung-yo.com/localStorage/market/257130/image/MAI_134135399_X400X400.jpg',
        text:'【奇哥】派對動物六層紗防踢背心禮盒',
        pricetext:'特價',
        price:'1290',
        },
        {
        id:'257139',
        link:'https://www.chung-yo.com/Product/257139',
        img:'https://www.chung-yo.com/localStorage/market/257139/image/MAI_140918602_X400X400.jpg',
        text:'【施巴】嬰兒洗沐組',
        pricetext:'特價',
        price:'1399',
        },
],

        //童裝 熱門標籤
        kidsbabytypeitem:[
            {   id: 0, 
                text: '奇哥',
                titletext:'更多奇哥商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14933',
            },
            {   id: 1, 
                text: '施巴',
                titletext:'更多施巴商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4827',
            },
            {   id: 2, 
                text: 'F\'ees',
                titletext:'更多F\'ees商品',
                link:'https://www.chung-yo.com/Product/CategoryL/2202',
            },
            {   id: 3, 
                text: '麗嬰房',
                titletext:'更多麗嬰房商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14932',
            },
            {   id: 4, 
                text: 'BAG TO YOU',
                titletext:'更多BAG TO YOU商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4839',
            },
            {   id: 5, 
                text: '大將作',
                titletext:'更多大將作商品',
                link:'https://www.chung-yo.com/Product/CategoryS/15201',
            },
        ],


//5.內睡衣 商品資訊
underwearitem: [
    {
        id:'256964',
        link:'https://www.chung-yo.com/Product/256964',
        img:'https://www.chung-yo.com/localStorage/market/256964/image/MAI_153739155_X400X400.jpg',
        text:'【La Vie Aisee金華歌爾】負5歲系列內衣',
        pricetext:'特價',
        price:'2682',
        },
        {
        id:'256979',
        link:'https://www.chung-yo.com/Product/256979',
        img:'https://www.chung-yo.com/localStorage/market/256979/image/MAI_155340512_X400X400.jpg',
        text:'【SWEAR思薇爾】花影饗宴系列內衣(清冰藍)',
        pricetext:'特價',
        price:'2142',
        },
        {
        id:'257162',
        link:'https://www.chung-yo.com/Product/257162',
        img:'https://www.chung-yo.com/localStorage/market/257162/image/MAI_153937104_X400X400.jpg',
        text:'【Triumph黛安芬】FLORALE團花錦簇V型無鋼圈內衣(羽紗橘)-BC罩杯',
        pricetext:'特價',
        price:'2502',
        },
        {
        id:'257166',
        link:'https://www.chung-yo.com/Product/257166',
        img:'https://www.chung-yo.com/localStorage/market/257166/image/MAI_154932410_X400X400.jpg',
        text:'【Modern Girl瑪登瑪朵】無限包覆款成套內衣兩套組-BCD罩杯',
        pricetext:'特價',
        price:'1940',
        },
        {
        id:'257170',
        link:'https://www.chung-yo.com/Product/257170',
        img:'https://www.chung-yo.com/localStorage/market/257170/image/MAI_155730345_X400X400.jpg',
        text:'【LADY ME】動物紋無鋼圈系列成套內衣兩套組(黑豹灰)-ABC罩杯',
        pricetext:'特價',
        price:'1280',
        },
],

        //內睡衣 熱門標籤
        underweartypeitem:[
            {   id: 0, 
                text: 'Aurdey奧黛莉',
                titletext:'更多Aurdey奧黛莉商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4818',
            },
            {   id: 1, 
                text: 'LADIES蕾黛絲',
                titletext:'更多LADIES蕾黛絲商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4819',
            },
            {   id: 2, 
                text: 'SAVVY莎薇',
                titletext:'更多SAVVY莎薇商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4925',
            },
            {   id: 3, 
                text: 'sloggi',
                titletext:'更多sloggi商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4896',
            },
            {   id: 4, 
                text: 'SWEAR思薇爾',
                titletext:'更多SWEAR思薇爾商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4820',
            },
            {   id: 5, 
                text: 'Triumph黛安芬',
                titletext:'更多Triumph黛安芬商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4821',
            },
        ],
    



//6.男裝 商品資訊
mensportitem:[
    {
        id:'256893',
        link:'https://www.chung-yo.com/Product/256893',
        img:'https://www.chung-yo.com/localStorage/market/256893/image/MAI_113705462_X400X400.jpg',
        text:'【K-SWISS】男女款老帽',
        pricetext:'特價',
        price:'522',
        },
        {
        id:'256896',
        link:'https://www.chung-yo.com/Product/256896',
        img:'https://www.chung-yo.com/localStorage/market/256896/image/MAI_114606695_X400X400.jpg',
        text:'【PONY】女款EVA輕量透氣洞洞鞋',
        pricetext:'特價',
        price:'990',
        },
        {
        id:'256898',
        link:'https://www.chung-yo.com/Product/256898',
        img:'https://www.chung-yo.com/localStorage/market/256898/image/MAI_115233809_X400X400.jpg',
        text:'【NEW BALANCE】中性款休閒涼鞋',
        pricetext:'特價',
        price:'2650',
        },
        {
        id:'256901',
        link:'https://www.chung-yo.com/Product/256901',
        img:'https://www.chung-yo.com/localStorage/market/256901/image/MAI_115933221_X400X400.jpg',
        text:'【SKECHERS】女款D LITE ULTRA時尚休閒鞋',
        pricetext:'特價',
        price:'1790',
        },
        {
        id:'256905',
        link:'https://www.chung-yo.com/Product/256905',
        img:'https://www.chung-yo.com/localStorage/market/256905/image/MAI_121130033_X400X400.jpg',
        text:'【KEEN】男女款UNEEK EXO戶外編織休閒鞋',
        pricetext:'特價',
        price:'2680',
        },
],

        //男裝 熱門標籤
        mensporttypeitem:[
            {   id: 0, 
                text: 'SPERRY',
                titletext:'更多SPERRY商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4840',
            },
            {   id: 1, 
                text: '歐都納',
                titletext:'更多歐都納商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4871',
            },
            {   id: 2, 
                text: 'CONVERSE',
                titletext:'更多CONVERSE商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4921',
            },
            {   id: 3, 
                text: 'CROCS',
                titletext:'更多CROCS商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4837',
            },
            {   id: 4, 
                text: 'KEEN',
                titletext:'更多KEEN商品',
                link:'https://www.chung-yo.com/Product/CategoryS/15303',
            },
            {   id: 5, 
                text: 'NIKE',
                titletext:'更多NIKE商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4923',
            },
        ],




//7.家用 商品資訊
homeneedsitem: [
    {
        id:'256340',
        link:'https://www.chung-yo.com/Product/256340',
        img:'https://www.chung-yo.com/localStorage/market/256340/image/MAI_124905830_X400X400.png',
        text:'【蕾莉歐】超音波香氛水氧機',
        pricetext:'特價',
        price:'1999',
        },
        {
        id:'256517',
        link:'https://www.chung-yo.com/Product/256517',
        img:'https://www.chung-yo.com/localStorage/market/256517/image/MAI_182211127_X400X400.jpg',
        text:'【IRIS OHYAMA】日本桌上型懶人負離子吹風機-佳醫',
        pricetext:'特價',
        price:'3280',
        },
        {
        id:'256857',
        link:'https://www.chung-yo.com/Product/256857',
        img:'https://www.chung-yo.com/localStorage/market/256857/image/MAI_192608199_X400X400.jpg',
        text:'【Hengstyle恆隆行】Sodastream Source氣泡水機',
        pricetext:'特價',
        price:'4990',
        },
        {
        id:'256866',
        link:'https://www.chung-yo.com/Product/256866',
        img:'https://www.chung-yo.com/localStorage/market/256866/image/MAI_194226601_X400X400.jpg',
        text:'【怡眾國際】Cuisinart多功能新纖果汁調理機(CPB-300TW)',
        pricetext:'特價',
        price:'1990',
        },
        {
        id:'256916',
        link:'https://www.chung-yo.com/Product/256916',
        img:'https://www.chung-yo.com/localStorage/market/256916/image/MAI_131111982_X400X400.jpg',
        text:'【金安德森】長纖萊賽爾天絲涼被 買一送一',
        pricetext:'特價',
        price:'5500',
        },
],

    //家用 熱門標籤
    homeneedstypeitem:[
        {   id: 0, 
            text: '嘉儀',
            titletext:'更多佳醫商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15162',
        },
        {   id: 1, 
            text: '匯聚',
            titletext:'更多匯聚商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15242',
        },
        {   id: 2, 
            text: 'Ucom益康屋',
            titletext:'更多Ucom益康屋商品',
            link:'https://www.chung-yo.com/Product/CategoryS/14847',
        },
        {   id: 3, 
            text: '元艇',
            titletext:'更多元艇商品',
            link:'https://www.chung-yo.com/Product/CategoryS/14837',
        },
        {   id: 4, 
            text: '歐萊德',
            titletext:'更多歐萊德商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15271',
        },
        {   id: 5, 
            text: '香草集',
            titletext:'更多香草集商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15221',
        },
    ],


    



//8.食品 商品資訊
fooditem: [
    {
        id:'255382',
        link:'https://www.chung-yo.com/Product/255382',
        img:'https://www.chung-yo.com/localStorage/market/255382/image/MAI_125350195_X400X400.png',
        text:'【大漢酵素】LaLa蔬孅粉2盒組',
        pricetext:'特價',
        price:'1577',
        },
        {
        id:'256062',
        link:'https://www.chung-yo.com/Product/256062',
        img:'https://www.chung-yo.com/localStorage/market/256062/image/MAI_101418271_X400X400.jpg',
        text:'【Diva Life 】比利時經典純巧克力片24片禮盒4盒組',
        pricetext:'特價',
        price:'1400',
        },
        {
        id:'256143',
        link:'https://www.chung-yo.com/Product/256143',
        img:'https://www.chung-yo.com/localStorage/market/256143/image/MAI_102523050_X400X400.jpg',
        text:'【古典玫瑰園】愛戀玫瑰按摩精油2罐組',
        pricetext:'特價',
        price:'1320',
        },
        {
        id:'256146',
        link:'https://www.chung-yo.com/Product/256146',
        img:'https://www.chung-yo.com/localStorage/market/256146/image/MAI_190116081_X400X400.jpg',
        text:'【GNC】松樹皮菁華食品錠(300錠)',
        pricetext:'特價',
        price:'9485',
        },
        {
        id:'256150',
        link:'https://www.chung-yo.com/Product/256150',
        img:'https://www.chung-yo.com/localStorage/market/256150/image/MAI_200110076_X400X400.jpg',
        text:'【GNC】LAC 晶白番茄粉末(30包 /盒)',
        pricetext:'特價',
        price:'2634',
        },
],

       //食品 熱門標籤
       foodtypeitem:[
            {   id: 0, 
                text: 'GNC',
                titletext:'更多GNC商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14822',
            },
            {   id: 1, 
                text: '美珍香',
                titletext:'更多美珍香商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14801',
            },
            {   id: 2, 
                text: '老行家',
                titletext:'更多老行家商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14803',
            },
            {   id: 3, 
                text: '長庚生技',
                titletext:'更多長庚生技商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4750',
            },
            {   id: 4, 
                text: '阿華師',
                titletext:'更多阿華師商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14799',
            },
            {   id: 5, 
                text: '古典玫瑰園',
                titletext:'更多古典玫瑰園商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4998',
            },
        ],



}})