var vuejsall= new Vue({
el: '#vuejsall',
data: {    



//電腦版banner 
//textbr:'黑白X丹寧', //新增段落
banneritem: [
    {   id: 0, 
        link:'https://www.chung-yo.com/promotion/2729',
        img:'images/banner/108-07-22/w/1220x500.jpg',
        title:'約會穿搭指南',
        text: '低調放閃4折起',
    },
    {   id: 1, 
        link:'https://www.chung-yo.com/promotion/2736',
        img:'images/banner/108-07-22/alb/BN_1220.jpg',
        title:'ALBION口碑商品',
        text: '健康化妝水',
        textbr:'45周年限定禮盒熱銷中', //新增段落
    },
    {   id: 2, 
        link:'https://www.chung-yo.com/promotion/2730',
        img:'images/banner/108-07-22/ck/1220x500.jpg',
        title:'CALVIN KLEIN',
        text: '搶眼時尚, 穿搭精品',
        textbr:'獨家6折起', //新增段落
    },
    {   id: 3, 
        link:'https://www.chung-yo.com/promotion/2725',
        img:'images/banner/108-07-22/MAN/1220x500-gif.gif',
        title:'MAN力爆棚',
        text: '型男必備選物',
    },
    {   id: 4, 
        link:'https://www.chung-yo.com/promotion/2724',
        img:'images/banner/108-07-22/OL/1220x500.jpg',
        title:'OL職場穿搭法則',
        text: '玩美3折起',
    },
    {   id: 8, 
        link:'https://www.chung-yo.com/event/restaurant/',
        img:'images/banner/108-07-22/food/1220x500.jpg',
        title:'中友人氣餐廳',
        text: '精選套餐7折起',
    },
],
//手機板banner 
banneritemm: [
   
    {   id: 0, 
        text: '低調放閃4折起',
        link:'https://www.chung-yo.com/promotion/2729',
        img:'images/banner/108-07-22/w/800x500-gif.gif',
    },

    {   id: 1, 
        text: '45周年限定禮盒熱銷中',
        link:'https://www.chung-yo.com/promotion/2736',
        img:'images/banner/108-07-22/alb/BN_800.jpg',
    },
    {   id: 2, 
        text: '獨家6折起',
        link:'https://www.chung-yo.com/promotion/2730',
        img:'images/banner/108-07-22/ck/800x500.jpg',
    },
    {   id: 3, 
        text: '型男必備選物',
        link:'https://www.chung-yo.com/promotion/2725',
        img:'images/banner/108-07-22/MAN/800x500-gif.gif',
    },
    {   id: 4, 
        text: '玩美3折起',
        link:'https://www.chung-yo.com/promotion/2724',
        img:'images/banner/108-07-22/OL/800x500.jpg',
    },
    
    {   id: 8, 
        text: '精選套餐7折起',
        link:'https://www.chung-yo.com/event/restaurant/',
        img:'images/banner/108-07-22/food/800x500.jpg',
    },
],







//1.化妝品 商品資訊
skincareitem:[
    {
        id:"218264",
        link:"https://www.chung-yo.com/Product/218264",
        img:"https://www.chung-yo.com/localStorage/market/218264/image/MAI_153825587_X400X400.jpg",
        text:"【CLINIQUE】男仕超電能保濕精華48ml",
        pricetext:"特價",
        price:"1700",
        },
        {
        id:"257822",
        link:"https://www.chung-yo.com/Product/257822",
        img:"https://www.chung-yo.com/localStorage/market/257822/image/MAI_112525762_X400X400.jpg",
        text:"【Benefit】陶瓷光底妝組",
        pricetext:"特價",
        price:"2400",
        },
        {
        id:"258149",
        link:"https://www.chung-yo.com/Product/258149",
        img:"https://www.chung-yo.com/localStorage/market/258149/image/MAI_142848491_X400X400.jpg",
        text:"【KOSE】雪肌精SAVE the BLUE守護海洋水潤組",
        pricetext:"特價",
        price:"1980",
        },
        {
        id:"258189",
        link:"https://www.chung-yo.com/Product/258189",
        img:"https://www.chung-yo.com/localStorage/market/258189/image/MAI_152457477_X400X400.jpg",
        text:"【SHISEIDO國際櫃】男人極致賦活水乳液80ml",
        pricetext:"特價",
        price:"1755",
        },
        {
        id:"258228",
        link:"https://www.chung-yo.com/Product/258228",
        img:"https://www.chung-yo.com/localStorage/market/258228/image/MAI_170209399_X400X400.jpg",
        text:"【SEACRET】男士刮鬍舒緩露組",
        pricetext:"特價",
        price:"1990",
        },
],

        //化妝品 熱門標籤
        makeuptypeitem:[
            {   id: 0, 
                text: '3INA',
                titletext:'更多3INA商品',
                link:'https://www.chung-yo.com/Product/CategoryS/15263',
            },   
            {   id: 1, 
                text: "GIORGIO ARMANI",
                titletext:'更多GIORGIO ARMANI商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4725',
            },   
            {   id: 2, 
                text: 'ESTEE LAUDER',
                titletext:'更多ESTEE LAUDER商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14811',
            },    
            {   id: 3, 
                text: 'GLAMGLOW',
                titletext:'更多GLAMGLOW艾杜紗',
                link:'https://www.chung-yo.com/Product/CategoryS/14812',
            },
            {   id: 4, 
                text: 'IPSA',
                titletext:'更多IPSA商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4745',
            },
            {   id: 5, 
                text: 'Jurlique',
                titletext:'更多Jurlique商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14817',
            },
        ],
    


//2.名品 商品資訊
internationalitem:[
   
    {
        id:"258632",
        link:"https://www.chung-yo.com/Product/258632",
        img:"https://www.chung-yo.com/localStorage/market/258632/image/MAI_115245966_X400X400.jpg",
        text:"【Samsonite】EVOA 20吋登機箱",
        pricetext:"特價",
        price:"10560",
        },
        {
        id:"258633",
        link:"https://www.chung-yo.com/Product/258633",
        img:"https://www.chung-yo.com/localStorage/market/258633/image/MAI_131809940_X400X400.jpg",
        text:"【GLORIA】BURBERRY墨鏡",
        pricetext:"特價",
        price:"4980",
        },
        {
        id:"258635",
        link:"https://www.chung-yo.com/Product/258635",
        img:"https://www.chung-yo.com/localStorage/market/258635/image/MAI_131657160_X400X400.jpg",
        text:"【Folli Follie】STYLE CODE+ FASHIONABLY SILVER米蘭腕錶項鍊組",
        pricetext:"特價",
        price:"10700",
        },
        {
        id:"258637",
        link:"https://www.chung-yo.com/Product/258637",
        img:"https://www.chung-yo.com/localStorage/market/258637/image/MAI_132950914_X400X400.jpg",
        text:"【COCCINELLE】撞色牛皮掀蓋方包",
        pricetext:"特價",
        price:"8600",
        },
        {
        id:"258826",
        link:"https://www.chung-yo.com/Product/258826",
        img:"https://www.chung-yo.com/localStorage/market/258826/image/MAI_132737229_X400X400.jpg",
        text:"【盧亞香水】Prada L'homme湛藍紳士男性淡香水組",
        pricetext:"特價",
        price:"3700",
        },
],

        //名品 熱門標籤
        internationaltypeitem: [
            {   id: 0, 
                text: 'SJ&J',
                titletext:'更多SJ&J商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=SJ%26J&',
            },
            {   id: 1, 
                text: 'FOSSIL',
                titletext:'更多FOSSIL商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=FOSSIL&',
            },
            {   id: 2, 
                text: 'Gloria',
                titletext:'更多Gloria商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=Gloria&',
            },
            {   id: 3, 
                text: 'COCCINELLE',
                titletext:'更多COCCINELLE商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=COCCINELLE',
            },
            {   id: 4, 
                text: 'Chloe',
                titletext:'更多Chloe商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=Chloe',
            },
            {   id: 5, 
                text: 'Samsonite',
                titletext:'更多Samsonite商品',
                link:'https://www.chung-yo.com/Search/Result?keyword=Samsonite',
            },
        ],
    

//3.服裝 商品資訊
accessoriesitem:[
    {
        id:"257735",
        link:"https://www.chung-yo.com/Product/257735",
        img:"https://www.chung-yo.com/localStorage/market/257735/image/MAI_144358615_X400X400.jpg",
        text:"【Benteau】永結同心鋼對鍊",
        pricetext:"特價",
        price:"2999",
        },
        {
        id:"257750",
        link:"https://www.chung-yo.com/Product/257750",
        img:"https://www.chung-yo.com/localStorage/market/257750/image/MAI_141840736_X400X400.jpg",
        text:"【Bo Derek】經典後背包",
        pricetext:"特價",
        price:"1500",
        },
        {
        id:"258552",
        link:"https://www.chung-yo.com/Product/258552",
        img:"https://www.chung-yo.com/localStorage/market/258552/image/MAI_141702247_X400X400.jpg",
        text:"【PORTER INTERNATIONAL】Hit the road系列側背包",
        pricetext:"特價",
        price:"4865",
        },
        {
        id:"258595",
        link:"https://www.chung-yo.com/Product/258595",
        img:"https://www.chung-yo.com/localStorage/market/258595/image/MAI_175116003_X400X400.jpg",
        text:"【California Republic】撞色動感圓領純棉T恤",
        pricetext:"特價",
        price:"1180",
        },
        {
        id:"258619",
        link:"https://www.chung-yo.com/Product/258619",
        img:"https://www.chung-yo.com/localStorage/market/258619/image/MAI_093753406_X400X400.jpg",
        text:"【FOSSIL】NEUTRA時尚流行計時手錶",
        pricetext:"特價",
        price:"5400",
        },
        {
        id:"258651",
        link:"https://www.chung-yo.com/Product/258651",
        img:"https://www.chung-yo.com/localStorage/market/258651/image/MAI_104521904_X400X400.jpg",
        text:"【8HAPPY】海洋度假風V領洋裝",
        pricetext:"特價",
        price:"1180",
        },
        {
        id:"258708",
        link:"https://www.chung-yo.com/Product/258708",
        img:"https://www.chung-yo.com/localStorage/market/258708/image/MAI_104205471_X400X400.jpg",
        text:"【Arnold palmer】條紋襯衫洋裝",
        pricetext:"特價",
        price:"2765",
        },
        {
        id:"258881",
        link:"https://www.chung-yo.com/Product/258881",
        img:"https://www.chung-yo.com/localStorage/market/258881/image/MAI_095718427_X400X400.jpg",
        text:"【be;eza】經典一字涼鞋",
        pricetext:"特價",
        price:"2980",
        },
        
],

        //服裝 熱們標籤
        accessoriestypeitem:[
            {   id: 0, 
                text: 'olivo',
                titletext:'更多olivo商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4959',
            },
            {   id: 1, 
                text: 'Arnold palmer包',
                titletext:'更多Arnold palmer包商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4918',
            },
            {   id: 2, 
                text: 'KnightsBridge',
                titletext:'更多KnightsBridge商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4964',
            },
            {   id: 3, 
                text: 'BOBSON',
                titletext:'更多BOBSON商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4808',
            },
            {   id: 4, 
                text: 'BIG TRAIN',
                titletext:'更多BIG TRAIN商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4807',
            },
            {   id: 5, 
                text: 'kiss kiss',
                titletext:'更多kiss kiss商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4908',
            },
        ],


            


//4.童裝 婦幼親子 商品資訊
kidsbabyitem: [
    {
        id:"258833",
        link:"https://www.chung-yo.com/Product/258833",
        img:"https://www.chung-yo.com/localStorage/market/258833/image/MAI_173310104_X400X400.jpg",
        text:"【chicco】套裝禮盒",
        pricetext:"特價",
        price:"999",
        },
        {
        id:"258834",
        link:"https://www.chung-yo.com/Product/258834",
        img:"https://www.chung-yo.com/localStorage/market/258834/image/MAI_173738768_X400X400.jpg",
        text:"【CONVERSE KIDS】經典LOGO上衣",
        pricetext:"特價",
        price:"435",
        },
        {
        id:"258836",
        link:"https://www.chung-yo.com/Product/258836",
        img:"https://www.chung-yo.com/localStorage/market/258836/image/MAI_173738768_X400X400.jpg",
        text:"【CONVERSE KIDS】針織短褲",
        pricetext:"特價",
        price:"480",
        },
        {
        id:"258837",
        link:"https://www.chung-yo.com/Product/258837",
        img:"https://www.chung-yo.com/localStorage/market/258837/image/MAI_174340637_X400X400.jpg",
        text:"【拼圖總動員】樹懶家族500片拼圖",
        pricetext:"特價",
        price:"488",
        },
        {
        id:"258839",
        link:"https://www.chung-yo.com/Product/258839",
        img:"https://www.chung-yo.com/localStorage/market/258839/image/MAI_174809115_X400X400.jpg",
        text:"【麗嬰房】Combi Loca手推車",
        pricetext:"特價",
        price:"9900",
        },
],

        //童裝 熱門標籤
        kidsbabytypeitem:[
            {   id: 0, 
                text: '奇哥',
                titletext:'更多奇哥商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14933',
            },
            {   id: 1, 
                text: '施巴',
                titletext:'更多施巴商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4827',
            },
            {   id: 2, 
                text: 'F\'ees',
                titletext:'更多F\'ees商品',
                link:'https://www.chung-yo.com/Product/CategoryL/2202',
            },
            {   id: 3, 
                text: '麗嬰房',
                titletext:'更多麗嬰房商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14932',
            },
            {   id: 4, 
                text: 'BAG TO YOU',
                titletext:'更多BAG TO YOU商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4839',
            },
            {   id: 5, 
                text: '大將作',
                titletext:'更多大將作商品',
                link:'https://www.chung-yo.com/Product/CategoryS/15201',
            },
        ],


//5.內睡衣 商品資訊
underwearitem: [
    {
        id:"242809",
        link:"https://www.chung-yo.com/Product/242809",
        img:"https://www.chung-yo.com/localStorage/market/242809/image/MAI_115037421_X400X400.jpg",
        text:"【Audrey奧黛莉】IONNO男士系列三角褲(藍灰色)",
        pricetext:"特價",
        price:"315",
        },
        {
        id:"258653",
        link:"https://www.chung-yo.com/Product/258653",
        img:"https://www.chung-yo.com/localStorage/market/258653/image/MAI_161939414_X400X400.jpg",
        text:"【Mode Marie曼黛瑪璉】DAYNEER男褲4件組",
        pricetext:"特價",
        price:"1440",
        },
        {
        id:"258658",
        link:"https://www.chung-yo.com/Product/258658",
        img:"https://www.chung-yo.com/localStorage/market/258658/image/MAI_162332592_X400X400.jpg",
        text:"【SAVVY莎薇】粉水2UP系列成套內衣2套組(慵懶膚)-BC罩杯",
        pricetext:"特價",
        price:"3621",
        },
        {
        id:"258664",
        link:"https://www.chung-yo.com/Product/258664",
        img:"https://www.chung-yo.com/localStorage/market/258664/image/MAI_163008789_X400X400.png",
        text:"【SAVVY莎薇】粉水2UP系列成套內衣2套組(骨董綠)-BC罩杯",
        pricetext:"特價",
        price:"3621",
        },
        {
        id:"258668",
        link:"https://www.chung-yo.com/Product/258668",
        img:"https://www.chung-yo.com/localStorage/market/258668/image/MAI_163613663_X400X400.jpg",
        text:"【LADIES蕾黛絲】百合無鋼圈靠過來成套內衣(嫩新黃)-CDE罩杯",
        pricetext:"特價",
        price:"1399",
        },
],

        //內睡衣 熱門標籤
        underweartypeitem:[
            {   id: 0, 
                text: 'Aurdey奧黛莉',
                titletext:'更多Aurdey奧黛莉商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4818',
            },
            {   id: 1, 
                text: 'LADIES蕾黛絲',
                titletext:'更多LADIES蕾黛絲商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4819',
            },
            {   id: 2, 
                text: 'SAVVY莎薇',
                titletext:'更多SAVVY莎薇商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4925',
            },
            {   id: 3, 
                text: 'Wacoal華歌爾',
                titletext:'更多Wacoal華歌爾商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4822',
            },
            {   id: 4, 
                text: 'SWEAR思薇爾',
                titletext:'更多SWEAR思薇爾商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4820',
            },
            {   id: 5, 
                text: 'Triumph黛安芬',
                titletext:'更多Triumph黛安芬商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4821',
            },
        ],
    



//6.男裝 商品資訊
mensportitem:[
    {
        id:"258312",
        link:"https://www.chung-yo.com/Product/258312",
        img:"https://www.chung-yo.com/localStorage/market/258312/image/MAI_153945317_X400X400.jpg",
        text:"【Timberland】荒野墨綠皮革休閒鞋",
        pricetext:"特價",
        price:"3430",
        },
        {
        id:"258644",
        link:"https://www.chung-yo.com/Product/258644",
        img:"https://www.chung-yo.com/localStorage/market/258644/image/MAI_164122386_X400X400.jpg",
        text:"【CERRUTI1881】皮帶禮盒組-上晏",
        pricetext:"特價",
        price:"5300",
        },
        {
        id:"258649",
        link:"https://www.chung-yo.com/Product/258649",
        img:"https://www.chung-yo.com/localStorage/market/258649/image/MAI_160150014_X400X400.jpg",
        text:"【NIKE】男女款REACT PRESTO魚骨襪套休閒鞋",
        pricetext:"特價",
        price:"3290",
        },
        {
        id:"258775",
        link:"https://www.chung-yo.com/Product/258775",
        img:"https://www.chung-yo.com/localStorage/market/258775/image/MAI_140217850_X400X400.jpg",
        text:"【ASICS】男款Gel Nimbus慢跑鞋",
        pricetext:"特價",
        price:"3346",
        },
        {
        id:"258778",
        link:"https://www.chung-yo.com/Product/258778",
        img:"https://www.chung-yo.com/localStorage/market/258778/image/MAI_141332751_X400X400.jpg",
        text:"【BROOKS】男款Neuro 3慢跑鞋",
        pricetext:"特價",
        price:"3290",
        },
        {
        id:"258788",
        link:"https://www.chung-yo.com/Product/258788",
        img:"https://www.chung-yo.com/localStorage/market/258788/image/MAI_144242893_X400X400.jpg",
        text:"【BAG TO YOU】OUTDOOR SMART系列18吋行李箱+PARTAKE商務公事包",
        pricetext:"特價",
        price:"4599",
        },
        {
        id:"258789",
        link:"https://www.chung-yo.com/Product/258789",
        img:"https://www.chung-yo.com/localStorage/market/258789/image/MAI_144907835_X400X400.jpg",
        text:"【KEEN】男款UNEEK編織涼鞋",
        pricetext:"特價",
        price:"2800",
        },
        {
        id:"258796",
        link:"https://www.chung-yo.com/Product/258796",
        img:"https://www.chung-yo.com/localStorage/market/258796/image/MAI_164449032_X400X400.jpg",
        text:"【E001】率性條紋獵裝",
        pricetext:"特價",
        price:"3495",
        },
],

        //男裝 熱門標籤
        mensporttypeitem:[
            {   id: 0, 
                text: 'SPERRY',
                titletext:'更多SPERRY商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4840',
            },
            {   id: 1, 
                text: '山頂鳥',
                titletext:'更多山頂鳥商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4884',
            },
            {   id: 2, 
                text: 'CONVERSE',
                titletext:'更多CONVERSE商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4921',
            },
            {   id: 3, 
                text: 'Columbia',
                titletext:'更多Columbia商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4886',
            },
            {   id: 4, 
                text: 'ASICS',
                titletext:'更多ASICS商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4833',
            },
            {   id: 5, 
                text: 'NIKE',
                titletext:'更多NIKE商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4923',
            },
        ],




//7.家用 商品資訊
homeneedsitem: [
    {
        id:"257665",
        link:"https://www.chung-yo.com/Product/257665",
        img:"https://www.chung-yo.com/localStorage/market/257665/image/MAI_204420081_X400X400.jpg",
        text:"【安妮莎琳】ROXETTE精梳棉印花雙人全套床組",
        pricetext:"特價",
        price:"3980",
        },
        {
        id:"258261",
        link:"https://www.chung-yo.com/Product/258261",
        img:"https://www.chung-yo.com/localStorage/market/258261/image/MAI_194601695_X400X400.jpg",
        text:"【法廚LE CREUSET】典藏圓鐵鍋16CM(鋼頭)+隔熱墊(櫻桃紅)",
        pricetext:"特價",
        price:"4280",
        },
        {
        id:"258296",
        link:"https://www.chung-yo.com/Product/258296",
        img:"https://www.chung-yo.com/localStorage/market/258296/image/MAI_143659076_X400X400.jpg",
        text:"【HUAWEI華為】nova 4e 6G/128G",
        pricetext:"特價",
        price:"10990",
        },
        {
        id:"258905",
        link:"https://www.chung-yo.com/Product/258905",
        img:"https://www.chung-yo.com/localStorage/market/258905/image/MAI_143700242_X400X400.jpg",
        text:"【飛利浦】荷蘭製君爵系列乾濕兩用三刀頭電鬍刀(S7910)",
        pricetext:"特價",
        price:"8888",
        },
        {
        id:"258909",
        link:"https://www.chung-yo.com/Product/258909",
        img:"https://www.chung-yo.com/localStorage/market/258909/image/MAI_145324151_X400X400.jpg",
        text:"【來思比】iRobot Roomba e5掃地機器人",
        pricetext:"特價",
        price:"19999",
        },
],

    //家用 熱門標籤
    homeneedstypeitem:[
        {   id: 0, 
            text: '匯聚',
            titletext:'更多匯聚商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15242',
        },
        {   id: 1, 
            text: '1929彼得兔',
            titletext:'更多1929彼得兔商品',
            link:'https://www.chung-yo.com/Product/CategoryS/14831',
        },
        {   id: 2, 
            text: '生活工場',
            titletext:'更多生活工場商品',
            link:'https://www.chung-yo.com/Product/CategoryS/14829',
        },
        {   id: 3, 
            text: 'DAY & DAY',
            titletext:'更多DAY & DAY商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15281',
        },
        {   id: 4, 
            text: '東妮寢飾',
            titletext:'更多東妮寢飾商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15270',
        },
        {   id: 5, 
            text: 'TIGER 虎牌',
            titletext:'更多TIGER 虎牌商品',
            link:'https://www.chung-yo.com/Product/CategoryS/15136',
        },
    ],


    



//8.食品 商品資訊
fooditem: [
    {
        id:"257196",
        link:"https://www.chung-yo.com/Product/257196",
        img:"https://www.chung-yo.com/localStorage/market/257196/image/MAI_175619981_X400X400.jpg",
        text:"【GODIVA】夏之戀巧克力心型禮盒(11顆裝)",
        pricetext:"特價",
        price:"1820",
        },
        {
        id:"257341",
        link:"https://www.chung-yo.com/Product/257341",
        img:"https://www.chung-yo.com/localStorage/market/257341/image/MAI_160437473_X400X400.jpg",
        text:"【老行家】元氣養蔘飲10入",
        pricetext:"特價",
        price:"780",
        },
        {
        id:"257343",
        link:"https://www.chung-yo.com/Product/257343",
        img:"https://www.chung-yo.com/localStorage/market/257343/image/MAI_191056719_X400X400.jpg",
        text:"【華齊堂】男霸龜露海參精(60ml*30入)",
        pricetext:"特價",
        price:"1380",
        },
        {
        id:"258269",
        link:"https://www.chung-yo.com/Product/258269",
        img:"https://www.chung-yo.com/localStorage/market/258269/image/MAI_111639210_X400X400.jpg",
        text:"【GNC】美佳男複方維他命食品錠(180錠)",
        pricetext:"特價",
        price:"1855",
        },
        {
        id:"258346",
        link:"https://www.chung-yo.com/Product/258346",
        img:"https://www.chung-yo.com/localStorage/market/258346/image/MAI_114023421_X400X400.jpg",
        text:"【大漢酵素】壯齡植蔬醱酵液(720ml) 買1送1",
        pricetext:"特價",
        price:"2200",
        },
],

       //食品 熱門標籤
       foodtypeitem:[
            {   id: 0, 
                text: 'GNC',
                titletext:'更多GNC商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14822',
            },
            {   id: 1, 
                text: '華陀扶元堂',
                titletext:'更多華陀扶元堂商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14810',
            },
            {   id: 2, 
                text: '華齊堂',
                titletext:'更多華齊堂商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14808',
            },
            {   id: 3, 
                text: '長庚生技',
                titletext:'更多長庚生技商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4750',
            },
            {   id: 4, 
                text: '阿華師',
                titletext:'更多阿華師商品',
                link:'https://www.chung-yo.com/Product/CategoryS/14799',
            },
            {   id: 5, 
                text: '古典玫瑰園',
                titletext:'更多古典玫瑰園商品',
                link:'https://www.chung-yo.com/Product/CategoryF/4998',
            },
        ],



}})